<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 4.0.6 on 2023-05-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Niños', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Niños',
            new_name='Niños_tabla',
        ),
    ]
=======
# Generated by Django 4.0.6 on 2023-05-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Niños', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Niños',
            new_name='Niños_tabla',
        ),
    ]
>>>>>>> 22ccbe2 (se avanza en comidas)
=======
# Generated by Django 4.0.6 on 2023-05-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Niños', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Niños',
            new_name='Niños_tabla',
        ),
    ]
>>>>>>> 651dabb795813a6afaad9cb5ddf0a630dfa85e34
